title: Evning
author: Evning
url: https://evning.studio # root address of the site
description: > # description of the site (multiple lines allowed)
  Evning description

permalink: /:slug.html

favicon: "./favicon.png" # relative path to site's favicon
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  back_home_text: "home.." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page
  show_navbar: true # show horizontal navbar in home page
  show_footer: true # show footer links in home page,add in _data/home.yml
  show_projects: true # show projects as cards, add in _data/home.yml
  show_old_projects: false # show old projects as cards, add in _data/home.yml
  show_misc_list: false # show generic vertical list for misc details, add _data/home.yml


sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag